name: Workflow - Skipping a job using conditional
run-name: Running Workflow that always skips a job

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print something
        run: echo "Hey! I am from job1"
  
  job2:
    if: false 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print something
        run: echo "Hey! I am from job2"
